#!/bin/bash

# ----------------- INSTALLATION OF SUPERVISOR ----------------- #

# ALLOW YOU TO RUN NODEJS
# PROGRAM AS A SERVICE
# IN DEBIAN AND UBUNTU
#

# -----------------        REQUIREMENT          ----------------- #

